# Start with a Nodejs base image
FROM node:22-bookworm AS builder

# Copy & build Frontend 
WORKDIR /app/frontend
COPY frontend/package.json ./
RUN npm install 
COPY frontend/ ./
RUN npm run build

# Create production image
FROM nginx:1.27-alpine AS production
COPY --from=builder /app/frontend/build/ /usr/share/nginx/html
COPY --from=builder /app/frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Start the nginx server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]