"""Weaviate ORM package."""

from .core import (
    WeaviateClient,
    ManagedConnection,
    ConnectionConfig,
    TimeoutConfig,
    EmbeddingsProvider,
    BedrockProvider,
    OpenAIProvider,
    create_provider_from_env,
    WeaviateClientRegistry,
    init_weaviate,
    get_weaviate_client,
    close_weaviate,
    LLMProvider,
    SearchType,
    WeaviateORMException,
    ConnectionException,
    ConfigurationException,
    QueryException,
    DoesNotExist,
    MultipleObjectsReturned,
    ValidationException,
    FieldValidationError,
    CollectionException,
    CollectionNotFound,
    InsertFailed,
)

from .models import (
    Model,
    TextField,
    IntField,
    FloatField,
    BooleanField,
    DateTimeField,
    UUIDField,
    TextArrayField,
    IntArrayField,
    FieldValidator,
    RequiredValidator,
    MaxLengthValidator,
    MinLengthValidator,
    RangeValidator,
    FieldConverter,
    DateTimeConverter,
    BoolConverter,
)

from .managers import (
    BatchResult,
    ObjectManager,
)

from .search import (
    Q,
    and_,
    or_,
    not_,
    QueryBuilder,
    AggregationBuilder,
)

__all__ = [
    'WeaviateClient',
    'ManagedConnection',
    'ConnectionConfig',
    'TimeoutConfig',
    'EmbeddingsProvider',
    'BedrockProvider',
    'OpenAIProvider',
    'create_provider_from_env',
    'WeaviateClientRegistry',
    'init_weaviate',
    'get_weaviate_client',
    'close_weaviate',
    'LLMProvider',
    'SearchType',
    'WeaviateORMException',
    'ConnectionException',
    'ConfigurationException',
    'QueryException',
    'DoesNotExist',
    'MultipleObjectsReturned',
    'ValidationException',
    'FieldValidationError',
    'CollectionException',
    'CollectionNotFound',
    'InsertFailed',
    'Model',
    'TextField',
    'IntField',
    'FloatField',
    'BooleanField',
    'DateTimeField',
    'UUIDField',
    'TextArrayField',
    'IntArrayField',
    'FieldValidator',
    'RequiredValidator',
    'MaxLengthValidator',
    'MinLengthValidator',
    'RangeValidator',
    'FieldConverter',
    'DateTimeConverter',
    'BoolConverter',
    'BatchResult',
    'ObjectManager',
    'Q',
    'and_',
    'or_',
    'not_',
    'QueryBuilder',
    'AggregationBuilder',
]

__version__ = '2.0.0'
